a=int(input("enter first number"))
b=int(input("enter second number"))
c=int(input("enter third number"))
d=float(input("enter fourth number"))
import math
print("sum of the number is:",a+b)
print("sub of the number is:",a-b)
print("mul of the number is:",a*b)
print("div of the number is:",a/b)
print("reminder of the number is:",b/c)
print("avg of the number is:",(a+b)/2)
print("round the number upto 2 dicimal place is:",round(d,2))
print("ceil the number is:",math.ceil(d))
print("floor the number is:",math.floor(d))